project:
  type: website
  output-dir: docs ############################## ajout

website:
  title: "todayyy"
  navbar:
    left:
      - href: index.qmd
        text: CeCi
      #- href: about.qmd
      - href: regex.qmd
      #- href: nest/nested_file.qmd

format:
  html:
    theme: cosmo
    #css: styles.css
    toc: true
